extensions:
  workfront/ui/1:
    $include: src/workfront-ui-1/ext.config.yaml

application:
  runtimeManifest:
    packages:
      workfront-custom-widget:
        license: Apache-2.0
        actions:
          get-workfront-task:
            function: actions/get-workfront-task/index.js
            web: 'yes'
            runtime: nodejs:18
            annotations:
              require-adobe-auth: false
              final: true
